from sqlalchemy import Column, Integer, String, DateTime, Text
from sqlalchemy.sql import func
from database.db import Base


class ScanHistory(Base):
    __tablename__ = "scan_history"
    # Uniqueness on scientific_name is enforced by a partial DB index
    # (created in main.py migration) so that NULL values are allowed.
    # Do NOT add a full UniqueConstraint here — it would reject NULL duplicates.

    id = Column(Integer, primary_key=True, index=True)
    plant_name = Column(String, nullable=False)
    scientific_name = Column(String, nullable=True)
    recommendation = Column(String, nullable=True)
    suitability_score = Column(Integer, nullable=True)
    details = Column(Text, nullable=True)  # full JSON from OpenAI
    image_path = Column(String, nullable=True)  # local file path on client
    scan_date = Column(DateTime(timezone=True), server_default=func.now())
    last_viewed_at = Column(DateTime(timezone=True), server_default=func.now())
    scan_count = Column(Integer, default=1)
    # Dynamic nursery price tiers (generated by pricing_service)
    price_small = Column(String, nullable=True)
    price_medium = Column(String, nullable=True)
    price_large = Column(String, nullable=True)
    # Pet safety (resolved by pet_safety_service, then AI fallback)
    pet_safety_status = Column(String, nullable=True)   # safe|caution|toxic|unknown
    pet_safety_source = Column(String, nullable=True)   # database|ai|unknown
